### ISSUE TITLE
[SafeAnchor] Unknown props `activeKey`, `activeHref` on <a> tag

### ISSUE THREAD

**Issue by Kallikrein** [react-bootstrap/react-router-bootstrap#203]
```
    Warning: Unknown props `activeKey`, `activeHref` on <a> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
        in a (created by SafeAnchor)
        in SafeAnchor (created by MenuItem)
        in li (created by MenuItem)
        in MenuItem (created by SGMenuItem)
        in LinkContainer (created by SGMenuItem)
        in SGMenuItem
        in ul (created by Nav)
        in Nav (created by Unknown)
        in Unknown
        in div (created by NavbarCollapse)
        in Transition (created by Collapse)
        in Collapse (created by NavbarCollapse)
        in NavbarCollapse (created by HeaderWithProps)
        in div (created by Grid)
        in Grid (created by Navbar)
        in nav (created by Navbar)
        in Navbar (created by Uncontrolled(Navbar))
        in Uncontrolled(Navbar) (created by HeaderWithProps)
        in header (created by HeaderWithProps)
        in HeaderWithProps (created by Decorated)
        in Decorated
        in component (created by RouterContext)
        in RouterContext (created by Router)
        in Router
        in IntlProvider (created by Unknown)
        in Unknown
```

**Comment by jquense** [comment]
Hi there, please upgrade your react-bootstrap, we've fixed all this errors many months ago at this point

**Comment by davidfurlong** [comment]
> Hi there, please upgrade your react-bootstrap, we've fixed all this errors many months ago at this point

I'm still having this issue, I'm on `react-bootstrap: 0.30.8`, `react-router-bootstrap: 0.23.1`, `react-router: 3.0.2`. Any ideas?

**Comment by juanpaco** [comment]
I'm still getting this with react-router-bootstrap 0.24.2 and react-bootstrap 0.31.1:

```
<MenuItem href="<some non-trivial href>">
  hi
</MenuItem>
```

**Comment by MimStha** [comment]
If you have used anchor tag (<a></a>) inside a React bootrap <Nav></Nav> like <Nav><a></a></Nav>, perhaps you might wanted to use Link for react router, you will need to install react-router-bootrap which provides a wrapper to <NavItem> which is similar to Link to.

 npm install -S react-router-bootstrap

 <Nav pullRight>
    <LinkContainer to="/admin">
          <NavItem><i className="glyphicon glyphicon-king"></i> Admin</NavItem>
    </LinkContainer>
 </Nav>

**Comment by MimStha** [comment]
If you used anchor tag (<a></a>) inside a React bootrap <Nav></Nav> like <Nav><a></a></Nav>, then  you might want to install react-router-bootrap which provides a wrapper to <NavItem> which is similar to Link to.
  -  npm install -S react-router-bootstrap

 <Nav pullRight>
    <LinkContainer to="/admin">
          <NavItem><i className="glyphicon glyphicon-king"></i> Admin</NavItem>
    </LinkContainer>
 </Nav>
